### PR TITLE
redo is no longer available on homebrew

### PR DESCRIPTION
**Pull request by llimllib**
Update the docs to reflect this

### CODE REVIEW

**Comment by fanninpm** [comment]
Apparently, it was deleted from Homebrew before #30 was implemented.

**Comment by llimllib** [comment]
Yeah I was unclear on that too, because the docs still say you need python 2.7. Should I update them to say something else - and what should they say?

**Comment by fanninpm** [comment]
I'm new to this repository, so take whatever I say with a huge helping of salt. Anyway, after I looked to see if [the latest release](https://github.com/apenwarr/redo/commit/a60949135dcc9f0cf6d7366c23ff3e8ea18ce915) included #30 (which it did), I may end up trying to submit a new formula to [homebrew/homebrew-core](https://github.com/homebrew/homebrew-core/). (I don't mean to devalue your contribution or anything…)

**Comment by llimllib** [comment]
That would be great! I would _love_ to close out this PR with that resolution

**Comment by fanninpm** [comment]
:tada: https://formulae.brew.sh/formula/redo :tada:

**Comment by llimllib** [comment]
Thanks!

**Pull request closed without merging**
